blank_issues_enabled: true
contact_links:
  - name: Question or idea
    url: https://github.com/zazieproductions/DAEDALUS-V.1/discussions
    about: For open-ended conversation about the project, its influences, or its methodology.
